#ifndef STATE_H
#define STATE_H

enum EntityState {
	//IDLING,
	FALLING,
	JUMPING,
	ON_GROUND,
	IDLING,
	STATE_IS_ACTIVE,
	STATE_IS_DYING,
	STATE_SHELL
};
enum SPRITE_STATE {
	NORMAL,
	STATE_TRANSITIONING_FROM_SMALL_TO_SUPER,
	STATE_TRANSITIONING_FROM_SUPER_TO_SMALL,
	STATE_TRANSITIONING_FROM_SMALL_TO_FIREBALL,
	STATE_TRANSITIONING_FROM_SUPER_TO_FIREBALL,
	STATE_TRANSITIONING_FROM_FIREBALL_TO_SMALL
};
#endif